## 精准度和召回率的平衡

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
from sklearn import datasets

digits = datasets.load_digits()
X = digits.data
y = digits.target.copy()

y[digits.target==9] = 1
y[digits.target!=9] = 0

In [3]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=666)

In [4]:
from sklearn.linear_model import LogisticRegression

log_reg = LogisticRegression()
log_reg.fit(X_train, y_train)
y_predict = log_reg.predict(X_test)

In [5]:
from sklearn.metrics import f1_score

f1_score(y_test, y_predict)

0.8674698795180723

In [6]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, y_predict)

array([[403,   2],
       [  9,  36]], dtype=int64)

In [7]:
from sklearn.metrics import precision_score

precision_score(y_test, y_predict)

0.9473684210526315

In [8]:
from sklearn.metrics import recall_score

recall_score(y_test, y_predict)

0.8

In [13]:
log_reg.decision_function(X_test)[:10]       #默认值决策分数值为0， 小于0为0，大于0为1

array([-22.05700117, -33.02940957, -16.21334087, -80.3791447 ,
       -48.25125396, -24.54005629, -44.39168773, -25.04292757,
        -0.97829292, -19.7174399 ])

In [14]:
log_reg.predict(X_test)[:10]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [15]:
decision_scores = log_reg.decision_function(X_test)

In [16]:
np.min(decision_scores)

-85.68608522646575

In [17]:
np.max(decision_scores)

19.8895858799022

In [18]:
y_predict_2 = np.array(decision_scores >= 5, dtype='int')

In [19]:
confusion_matrix(y_test, y_predict_2)

array([[404,   1],
       [ 21,  24]], dtype=int64)

In [20]:
recall_score(y_test, y_predict_2)

0.5333333333333333

In [21]:
precision_score(y_test, y_predict_2)

0.96

In [22]:
y_predict_3 = np.array(decision_scores >= -5, dtype='int')

In [23]:
confusion_matrix(y_test, y_predict_3)

array([[390,  15],
       [  5,  40]], dtype=int64)

In [24]:
precision_score(y_test, y_predict_3)

0.7272727272727273

In [25]:
recall_score(y_test, y_predict_3)

0.8888888888888888