# numpy.array基础

In [1]:
import numpy

In [5]:
numpy.__version__

'1.14.3'

In [13]:
import numpy as np

In [14]:
np.__version__

'1.14.3'

# Python List的特点

In [15]:
L=[i for i in range(10)]
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [18]:
L[5]="lala"
L

[0, 1, 2, 3, 4, 'lala', 6, 7, 8, 9]

### 上面元素可以改变，程序需要去判别数据类型，影响速率

In [20]:
import array

In [22]:
arr = array.array('i', [i for i in range(10)])

In [23]:
arr

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
arr[5]

5

In [25]:
arr[5] = 100

In [26]:
arr

array('i', [0, 1, 2, 3, 4, 100, 6, 7, 8, 9])

'i'定义了为整数，不能更换为字符串。

# numpy.array

In [27]:
nparr = np.array([i for i in range(10)])
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
nparr[5]

5

In [29]:
nparr[5] = 100
nparr

array([  0,   1,   2,   3,   4, 100,   6,   7,   8,   9])

也不能更换别的数据类型,只接受整数，小数也会被取整

In [30]:
nparr.dtype

dtype('int32')

In [31]:
nparr2 = np.array([1, 2, 3.])

In [33]:
nparr2.dtype

dtype('float64')

### 其他创建numpy.array的方法

In [34]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [35]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [36]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [37]:
np.zeros(shape=(3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [39]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [40]:
np.full(shape=(3,5),fill_value=6)

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]])

### arange

In [41]:
[i for i in range(0, 20, 2)]

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [42]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

### linspace

In [43]:
np.linspace(0,20,10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [44]:
np.linspace(0,20,11)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

### random

In [45]:
np.random.randint(0,10)

4

In [46]:
np.random.randint(0, 10, 10)

array([4, 2, 8, 0, 6, 9, 9, 5, 4, 6])

In [47]:
np.random.randint(0, 1, 10)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [48]:
np.random.randint(0, 10, size=10)

array([6, 3, 4, 6, 0, 8, 6, 5, 0, 0])

In [49]:
np.random.randint(0, 10, size=(3,5))

array([[3, 8, 7, 3, 6],
       [3, 6, 0, 4, 0],
       [7, 1, 8, 9, 9]])

### 随机种子，使俩次随机的矩阵相同

In [50]:
np.random.seed(666)
np.random.randint(0, 10, size=(3,5))

array([[2, 6, 9, 4, 3],
       [1, 0, 8, 7, 5],
       [2, 5, 5, 4, 8]])

In [51]:
np.random.seed(666)
np.random.randint(0, 10, size=(3,5))

array([[2, 6, 9, 4, 3],
       [1, 0, 8, 7, 5],
       [2, 5, 5, 4, 8]])

In [52]:
np.random.random()

0.7315955468480113

In [53]:
np.random.random(10)

array([0.8578588 , 0.76741234, 0.95323137, 0.29097383, 0.84778197,
       0.3497619 , 0.92389692, 0.29489453, 0.52438061, 0.94253896])

In [54]:
np.random.random((3,5))

array([[0.07473949, 0.27646251, 0.4675855 , 0.31581532, 0.39016259],
       [0.26832981, 0.75366384, 0.66673747, 0.87287954, 0.52109719],
       [0.75020425, 0.32940234, 0.29130197, 0.00103619, 0.6361797 ]])

#### 符合正太分布的随机浮点数

In [55]:
np.random.normal()

-1.5644858645303779

In [58]:
np.random.normal(10,100)      均值为10，方差为100

133.17486561462027

In [59]:
np.random.normal(0 ,1,(3,5))

array([[-0.91360034, -0.27084407,  1.42024914, -0.98226439,  0.80976498],
       [ 1.85205227,  1.67819021, -0.98076924,  0.47031082,  0.18226991],
       [-0.84388249,  0.20996833,  0.22958666,  0.26307642,  2.16633222]])

In [60]:
np.random.normal? 

In [62]:
help(np.random.normal)

Help on built-in function normal:

normal(...) method of mtrand.RandomState instance
    normal(loc=0.0, scale=1.0, size=None)
    
    Draw random samples from a normal (Gaussian) distribution.
    
    The probability density function of the normal distribution, first
    derived by De Moivre and 200 years later by both Gauss and Laplace
    independently [2]_, is often called the bell curve because of
    its characteristic shape (see the example below).
    
    The normal distributions occurs often in nature.  For example, it
    describes the commonly occurring distribution of samples influenced
    by a large number of tiny, random disturbances, each with its own
    unique distribution [2]_.
    
    Parameters
    ----------
    loc : float or array_like of floats
        Mean ("centre") of the distribution.
    scale : float or array_like of floats
        Standard deviation (spread or "width") of the distribution.
    size : int or tuple of ints, optional
        Output shap

## 合并

In [63]:
x = np.array([1,2,3])

In [64]:
y = np.array([1,2,3])

In [65]:
np.concatenate([x,y])

array([1, 2, 3, 1, 2, 3])

In [67]:
A = np.array([[1,2,3],[1,2,3]])

In [68]:
np.concatenate([A,A])

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [69]:
np.concatenate([A,A],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3]])

In [71]:
np.concatenate([A,x.reshape(1, -1)])

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [72]:
A

array([[1, 2, 3],
       [1, 2, 3]])

In [73]:
np.vstack([A,y])

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [74]:
np.hstack([A,A])

array([[1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3]])

In [75]:
np.hstack([A,y])

ValueError: all the input arrays must have same number of dimensions

### 分割

In [76]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [77]:
x1, x2, x3 = np.split(x,[3,7])

In [78]:
x1

array([0, 1, 2])

In [79]:
x2

array([3, 4, 5, 6])

In [80]:
x3

array([7, 8, 9])

In [81]:
data = np.arange(16).reshape((4,4))
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [82]:
x ,y = np.hsplit(data,[-1])

In [83]:
x

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

In [84]:
y

array([[ 3],
       [ 7],
       [11],
       [15]])

In [85]:
y[:,0]

array([ 3,  7, 11, 15])

### 求逆矩阵

In [ ]:
invA = np.linalg.inv(v)

In [ ]:
invA = np.linalg.pinv(v)   求伪逆，不是正方阵