In [123]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets

In [124]:
iris = datasets.load_iris()

In [125]:
X = iris.data
y = iris.target

In [126]:
X.shape

(150, 4)

In [127]:
y.shape

(150,)

## train_test_split  把样本分成俩部分，大部分用来训练，小部分用来测试

In [128]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [129]:
shuffle_indexes = np.random.permutation(len(X))

In [130]:
shuffle_indexes

array([ 98, 130,  31, 131,  65,  62,  68, 134,  48,  59,  40,   5, 135,
        77,  42,  55,  11,  28,  53,  74,  58,  38,  97,  52,  51,  27,
        44, 112,  70, 126,  14,  36,   6,   4,  57, 119, 115,  73,  95,
       124, 122,  22, 145,  71,   8,  33,  78,  61,  87,  45,  85, 116,
       125,  94,   1, 107, 133,   3,  92, 120,  54, 132,  50,  19, 111,
       117, 100,  17, 109,  80, 123,   0, 137,  56,  32,  43, 105, 106,
       149,  10,  63, 136,  49, 114,  66,  79, 144, 129,  41,   9,  13,
       148, 104,  83,  84,  12, 103,  99, 113, 121,  23, 141, 146, 142,
        21,   2, 110,  76,  91,  37,  60,  29,  39,  24,  69,  93,  35,
        64,  72, 147,  16,  86,  67,  75,  34, 139,  96,  46,  30,  90,
        81, 127,   7, 140, 143,  26, 138,  20,  15,  18, 101, 128, 102,
        25,  47, 108, 118,  88,  82,  89])

In [131]:
test_ratio = 0.2
test_size =int(len(X)*test_ratio)
test_size

30

In [132]:
test_indexes = shuffle_indexes[:test_size]
train_indexes = shuffle_indexes[test_size:]

In [133]:
X_train = X[train_indexes]
y_train = y[train_indexes]

X_test = X[test_indexes]
y_test = y[test_indexes]

In [134]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [135]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)


### 使用我们的算法split数据集

In [136]:
from playML.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y)

In [137]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [138]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)


### 测试我们的算法

In [139]:
from playML.kNN import KNNClassifier

In [140]:
my_knn_clf = KNNClassifier(k=3)

In [141]:
my_knn_clf.fit(X_train ,y_train)

KNN(k=3)

In [142]:
y_test

array([1, 0, 1, 1, 2, 1, 0, 1, 1, 0, 0, 0, 2, 2, 2, 1, 2, 2, 1, 0, 2, 2,
       0, 2, 1, 1, 0, 2, 1, 1])

In [143]:
y_predict = my_knn_clf.predict(X_test)
y_predict

array([1, 0, 1, 1, 2, 1, 0, 1, 1, 0, 0, 0, 2, 2, 2, 1, 2, 2, 1, 0, 2, 2,
       0, 2, 1, 2, 0, 2, 1, 1])

In [144]:
sum(y_predict == y_test)

29

In [145]:
sum(y_predict == y_test) / len(y_test)

0.9666666666666667

### sklearn中的train_test_split

In [146]:
from sklearn.model_selection import train_test_split

train_test_split

<function sklearn.model_selection._split.train_test_split(*arrays, **options)>

In [147]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=666)

In [148]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [149]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)
